version: '3'
services:
  script:
    build: .
    container_name: "sse_script"
    image: debian:latest
    stdin_open: true
    tty: true
    links:
    - mongo
    depends_on:
    - mongo
  mongo:
    image: mongo:latest
    ports:
    - "27017:27017"